Tensorflow pr 1.3
epfl-scitas/spack pull request #103
Opened 2017-09-13 12:12 UTC by nvarini

2017-09-15 14:38 UTC, alalazo requested changes
This package needs some clean-up, in particular the docstring which will be used to generate module files.

2017-09-15 14:38 UTC, alalazo commented on var/spack/repos/builtin/packages/tensorflow/package.py
> +    """Tensorflow external package
This is what we'll be writing in module files. Can you put a more sensible description? Ideally it should be a short and sweat first paragraph (will be module whatis) followed by a broader explanation (module help).

2017-09-15 14:38 UTC, alalazo commented on var/spack/repos/builtin/packages/tensorflow/package.py
> +    depends_on('python')
As this is a fake package, please remove every `depends_on` (they don't make sense as we don't build the package with Spack).

2017-09-15 14:38 UTC, alalazo commented on var/spack/repos/builtin/packages/tensorflow/package.py
> +                     1.3.0/tensorflow_venv_gpu/'
:astonished:

2017-09-15 14:39 UTC, nvarini commented on var/spack/repos/builtin/packages/tensorflow/package.py
> +    """Tensorflow external package
Ok, I just followed the description for the tensorflow packaged deployed with lafnestcha

2017-09-15 14:40 UTC, nvarini commented on var/spack/repos/builtin/packages/tensorflow/package.py
> +                     1.3.0/tensorflow_venv_gpu/'
??

2018-01-23 06:57 UTC, alalazo commented
Closing this as inactive for a while. Feel free to reopen if you have a recipe for tensorflow

2018-01-23 06:57 UTC, closed without merging