SRA Toolkit binary package
epfl-scitas/spack pull request #125
Opened 2017-12-21 21:47 UTC by matteoguglielmi

SRA Toolkit external package

2018-01-20 22:13 UTC, matteoguglielmi commented
sra-tools external package

2018-01-22 15:20 UTC, alalazo requested changes
The sources are available. Why do you use generic pre-built binaries instead?

2018-01-22 15:20 UTC, alalazo commented on var/spack/repos/builtin/packages/sra-tools/package.py
> +    url      = "http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-centos_linux64.tar.gz"
There's no point in using a package manager that can build packages from source, if we use generic pre-built binaries :wink:  Github repository [here](https://github.com/ncbi/sra-tools)

2018-01-22 15:20 UTC, alalazo commented on var/spack/repos/builtin/packages/sra-tools/package.py
> +#
Please remove comment from here below, before resubmitting

2018-02-10 13:18 UTC, closed without merging