Added CP2K_DATA_DIR and copied needed files to the tree
epfl-scitas/spack pull request #199
Opened 2018-10-08 13:26 UTC by batatasfritas

By default CP2K will look for some important files (basis sets, etc) in a directory relative to the source tree location during the make. The recipe now copies these files to the destination directory (self.prefix.data) and adds an environment variable to the runtime environment.

2018-10-09 10:46 UTC, rmsds requested changes

2018-10-09 10:46 UTC, rmsds commented on var/spack/repos/builtin/packages/cp2k/package.py
> +        run_env.set('CP2K_DATA_DIR', self.prefix + '/data/')
You really should use `os.path.join()` here, or maybe you could even use `self.prefix.data` directly? (But I'm not really sure about this one.)

2018-10-09 10:46 UTC, rmsds commented on var/spack/repos/builtin/packages/cp2k/package.py
> +        shutil.copytree('data', self.prefix.data)
You could also use the built-in [install_tree](https://spack.readthedocs.io/en/latest/llnl.util.html?highlight=install_tree#llnl.util.filesystem.install_tree) (which I just discovered today :) ), but either solution is fine.

2018-10-09 10:59 UTC, batatasfritas commented on var/spack/repos/builtin/packages/cp2k/package.py
> +        run_env.set('CP2K_DATA_DIR', self.prefix + '/data/')
I thought os.path.join would strip the trailing slash I have on the data. CP2K_DATA_DIR must have it. After your comment I ttok a look at this and I just confirmed that it doesn't, so os.path.join should work. I'll update this. self.prefix.data won't work though, since it will not put the slash (if I understand it correctly, correct me if I'm wrong).

2018-10-09 10:59 UTC, batatasfritas commented on var/spack/repos/builtin/packages/cp2k/package.py
> +        shutil.copytree('data', self.prefix.data)
Good to know about this. In this specific case, since these are just world-readable text files it won't change much. But in other cases it definitely makes a difference. Thanks!

2018-10-11 14:09 UTC, rmsds commented on var/spack/repos/builtin/packages/cp2k/package.py
> +        data_path = os.path.join(self.prefix, 'data/')
I think it should be `os.path.join(pre, 'data{0}'.format(os.path.sep))`

2018-10-17 08:32 UTC, rmsds commented on var/spack/repos/builtin/packages/cp2k/package.py
> +        data_path = os.path.join(self.prefix, 'data/')
And now, using the brand new Github suggestion feature:
```suggestion
        data_path = os.path.join(self.prefix, 'data{0}'.format(os.path.sep))
```

2018-10-19 11:27 UTC, rmsds approved these changes

2018-11-07 10:29 UTC, alalazo approved these changes

2018-11-16 10:38 UTC, rmsds commented
Depends on #201, should be merged after it.

2018-12-13 10:02 UTC, merged