Packages/libxc
epfl-scitas/spack pull request #201
Opened 2018-10-10 08:49 UTC by batatasfritas

Updated the supported versions.
Changed the URL and added individual URLs for the two versions that are different.
LibXC 4.x is needed for CP2K 6.1. So this has to be pushed upstream together/before CP2K 6.1 updates

2018-10-17 08:39 UTC, rmsds requested changes
I think you accidentally based this branch on the CP2K changes used in #199.
Could you `git rebase -i origin/releases/paien` and drop the CP2K commit?
Otherwise it looks OK.

2018-11-16 11:47 UTC, rmsds requested changes
I think this is what is missing for flake8 to be happy.

2018-11-16 11:47 UTC, rmsds commented on var/spack/repos/builtin/packages/libxc/package.py
> +            url = 'http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-2.2.2.tar.gz')
```suggestion
            url='http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-2.2.2.tar.gz')
```

2018-11-16 11:47 UTC, rmsds commented on var/spack/repos/builtin/packages/libxc/package.py
> +            url = 'http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-2.2.1.tar.gz')
```suggestion
            url='http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-2.2.1.tar.gz')
```

2018-11-16 13:51 UTC, rmsds approved these changes

2018-11-16 13:58 UTC, rmsds approved these changes

2018-11-16 16:56 UTC, rmsds commented
I think we need to change our CP2K spec in [https://github.com/epfl-scitas/spack-packagelist] to explicitly depend on `^libxc@3.0.0` before we merge this one. Otherwise a new CP2K 5.1 will be installed against the latest libxc: 4.2.3.

2018-11-22 14:58 UTC, rmsds commented
Depends on https://github.com/epfl-scitas/spack-packagelist/pull/124

2018-12-04 12:56 UTC, alalazo commented
@rmsds I updated the branch. Can you check if this is fine to be merged if all the tests go green?

2018-12-05 12:36 UTC, rmsds approved these changes
Looks good now, will merge once the updated checks go green.

2018-12-07 12:34 UTC, merged