sicer: new package
epfl-scitas/spack pull request #204
Opened 2018-10-17 15:04 UTC by rmsds

2018-10-17 15:36 UTC, rmsds commented
See #205 instead.

2018-10-17 15:37 UTC, rmsds commented
@alalazo would like your insight on why this one fails (thinks things changed in the list of tested core packages).

2018-10-17 16:26 UTC, nrichart requested changes

2018-10-17 16:26 UTC, nrichart commented on var/spack/repos/builtin/packages/sicer/package.py
> +        chmod('a+x', os.path.join(prefix.SICER, 'SICER.sh'))
to make it portable
```
import os
import stat

st = os.stat('somefile')
os.chmod('somefile', st.st_mode | stat.S_IEXEC)
```

2018-10-18 09:07 UTC, rmsds commented on var/spack/repos/builtin/packages/sicer/package.py
> +        chmod('a+x', os.path.join(prefix.SICER, 'SICER.sh'))
I went with the spack builtin `set_executable()`.

I found it when investigating why stat didn't work, stat was actually overridden by a spack builtin within the class.

2018-10-24 13:33 UTC, closed without merging