Score p
epfl-scitas/spack pull request #213
Opened 2018-11-06 15:21 UTC by nvarini

2018-11-07 09:01 UTC, rmsds requested changes

2018-11-07 09:01 UTC, rmsds commented on var/spack/repos/builtin/packages/scorep/package.py
> +    patch('gcc7.patch',when='gcc%7i:')
Not sure about the syntax here for the `when=`, did you mean this?
```suggestion
    patch('gcc7.patch', when='%gcc@7:')
```
(A space was missing a space which makes flake8 unhappy.)

2018-11-07 09:01 UTC, rmsds commented on var/spack/repos/builtin/packages/scorep/package.py
> +    depends_on('cube')
If it's under the above comment should this be?
```suggestion
    depends_on('cube', when='@3:')
```
Or is it a general dependency for all scorep versions?

2018-11-07 14:06 UTC, alalazo requested changes
There's a typo in one of the constraints.

2018-11-07 14:06 UTC, alalazo commented on var/spack/repos/builtin/packages/scorep/package.py
> +    patch('gcc7.patch', when='gcc%7:')
I think there's an error here: it should be `when=gcc@7:` i.e. it should be using `@` and not `%`.

2018-11-08 08:28 UTC, alalazo approved these changes

2018-11-08 08:29 UTC, alalazo commented
Apparently Travis went green, but the notification to Github wasn't pushed. Waiting for @rmsds to check and eventually merge.

2018-11-08 09:23 UTC, rmsds approved these changes

2018-11-08 10:08 UTC, merged