Caffe with and without CUDA support. It has been tested on gcc so far.
epfl-scitas/spack pull request #45
Opened 2016-10-21 12:45 UTC by nvarini

Additional packages like py-pytest and cudnn has been created

2016-11-25 08:50 UTC, alalazo requested changes
Major problems: `gcc` and `openblas` are hardcoded. This  means that at install time we cannot use other compilers or lapack providers.

The `--override` option in cuda is probably worth a look, as what it overrides very likely depend on the version of cuda installed.

The rest of the comments are just on the implementation.

2016-11-25 08:50 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +# This is a template package file for Spack.  We've put "FIXME"
Remove the FIXMEs, as already asked in #32

2016-11-25 08:52 UTC, alalazo requested changes
Major problems: `gcc` and `openblas` are hardcoded. This  means that at install time we cannot use other compilers or lapack providers.

The `--override` option in cuda is probably worth a look, as what it overrides very likely depend on the version of cuda installed.

The rest of the comments are just on the implementation.

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +    # FIXME: Add a proper url for your package's homepage here.
Remove the FIXME as already asked in #32

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +    version('2', 'c331932e34b5e2f5022fcc34c419080f')
Version numbering is wrong: these are not version 2 and 3, but rc2 and rc3

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +    # FIXME: Add additional dependencies if required.
Remove the FIXME as already asked in #32

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +    #depends_on('python')
Remove the comment

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +    depends_on('openblas')
Does caffe depend only on openblas? Or it depends on `lapack`?

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +            cmake_args.append("-DBLAS=open" )
Is this hard-coded to use just `openblas`? If so why?

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +            cmake_args.append("-DCMAKE_C_COMPILER=gcc")
Remove these two lines, otherwise `caffe` will always try to compile with `gcc` even if another compiler is used in the spec.

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +              cmake_args.append("-DCUDNN_LIBRARY=%s"%spec['cudnn'].prefix.lib+'/libcudnn.so')
Use `join_path` when constructing paths:
```
join_path(spec['cudnn'].prefix.lib, 'libcudnn.so')
```
as '/' is not always portable across architectures. Another thing: is it mandated by the cuda toolkit to link a static AND a dynamic library ?

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/cuda/package.py
> +            '--override',  # Error: unsupported compiler: 4.9.3. Use --override
What does `--override` do, it would be nice to add a comment here as it seems an option that could introduce some subtle behaviors...

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/cudnn/package.py
> +from shutil import copytree
You don't need copytree. There should be already `llnl.util.filesystem.install_tree` doing the same thing AND setting install permissions.

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/cudnn/package.py
> +    url      = "file:///home/nvarini/spack_cudnn/cudnn-7.0-linux-x64-v4.0-prod.tgz"
Hmmm, do you want to leave your home in the URL? :smile:

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/cudnn/package.py
> +        includedir=os.getcwd()+'/include'
Why do you need this ? You are already in `os.getcwd()`. I think that all the `install` body here can be written as:
```python
install_tree('lib64', prefix.lib)
install_tree('include', prefix.include)
```

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pytest/package.py
> +# This is a template package file for Spack.  We've put "FIXME"
Remove the FIXME

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pytest/package.py
> +    # FIXME: add a proper url for your package's homepage here.
Remove the FIXME

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pytest/package.py
> +    # FIXME: Add dependencies if this package requires them.
Remove the FIXME

2016-11-25 08:52 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pytest/package.py
> +    # depends_on("foo")
Remove the comment

2016-11-25 08:53 UTC, alalazo commented
Apologies for double posting: for some reasons github took only the first comment the first time I submitted the review.

2016-11-25 09:20 UTC, nvarini commented on var/spack/repos/builtin/packages/caffe/package.py
> +    # FIXME: Add a proper url for your package's homepage here.
Ok for gcc. With re openblas the blas selection is described here:
http://caffe.berkeleyvision.org/installation.html
Is there a way in spack to specify  BLAS := open, BLAS := mkl or BLAS = atlas depeding from the BLAS installed?

2016-11-25 09:41 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +    # FIXME: Add a proper url for your package's homepage here.
Yes:
```
depends_on('lapack')
```
then in the install method:
```python
if 'openblas' in spec:
    # do something openblas specific
elif 'mkl' in spec:
    # do something mkl specific
elif 'atlas' in spec:
    # ...
else:
    # raise an error

2016-11-25 09:45 UTC, alalazo commented
@nvarini Did you have a look at [this](https://github.com/intel/caffe) ?

2016-11-25 09:49 UTC, nvarini commented
I did not know. But this fork is specific to Intel® Xeon Phi processors. AFAIK we have more interest in caffe for GPU. 
What do you suggest?

2016-11-25 09:55 UTC, alalazo commented
@nvarini The part that seemed interesting is multi-node training in the intel distribution, i.e. no GPUs but multiple nodes. We can defer this to another PR if you think it's the case.

2016-11-25 10:09 UTC, alalazo commented
Just finished compiling with `gcc` and `cuda`.  As soon as the comments will be addressed I'll re-try the compilation adding `intel` to the mix. Then for me it will be ready to merge.

2016-11-25 15:42 UTC, nvarini commented on var/spack/repos/builtin/packages/cudnn/package.py
> +    url      = "file:///home/nvarini/spack_cudnn/cudnn-7.0-linux-x64-v4.0-prod.tgz"
how do you get the file cudnn-7.0-linux-x64-v4.0-prod.tgz?

2016-11-25 16:13 UTC, alalazo commented on var/spack/repos/builtin/packages/cudnn/package.py
> +    url      = "file:///home/nvarini/spack_cudnn/cudnn-7.0-linux-x64-v4.0-prod.tgz"
You have to put it in a mirror if you cannot download it directly. I was just wondering if you want to leave your `home` here: when the package will be ready we'll try to contribute it upstream.

2016-11-25 16:32 UTC, nvarini commented on var/spack/repos/builtin/packages/cudnn/package.py
> +    url      = "file:///home/nvarini/spack_cudnn/cudnn-7.0-linux-x64-v4.0-prod.tgz"
Yes I know, but there is something strange:
p[nvarini@deneb2 packages]$ spack mirror list
/home/nvarini/spack_cudnn/    https://developer.nvidia.com/cudnn
local                         file:///home/nvarini/spack_cudnn/
[nvarini@deneb2 packages]$ ls /home/nvarini/spack_cudnn/
cudnn-7.0-linux-x64-v4.0-prod.tgz  hdf5  tensorflow

[nvarini@deneb2 packages]$ spack install -v --keep-stage caffe +cuda ^ openblas % gcc@4.9.3
==> Error: Class constructor failed for package 'cudnn'.

Caused by:
NoURLError: Package Cudnn has no version with a URL.
  File "/home/nvarini/spack-trunk/lib/spack/spack/repository.py", line 561, in get
    self._instances[key] = package_class(copy)
  File "/home/nvarini/spack-trunk/lib/spack/spack/package.py", line 374, in __init__
    f = fs.for_package_version(self, self.version)
  File "/home/nvarini/spack-trunk/lib/spack/spack/fetch_strategy.py", line 810, in for_package_version
    attrs['url'] = pkg.url_for_version(version)
  File "/home/nvarini/spack-trunk/lib/spack/spack/package.py", line 462, in url_for_version
    raise NoURLError(cls)

This happen after having removed url statement. How can you tell spack which file has to get from the mirror?

Thanks!

2016-12-06 09:29 UTC, alalazo requested changes
I think something went wrong with your latest commits. QE is still there and so the comments to be removed.

2016-12-06 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/caffe/package.py
> +# This is a template package file for Spack.  We've put "FIXME"
@nvarini The FIXME is still there...

2016-12-06 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/cudnn/package.py
> +    url      = "file:///home/nvarini/spack_cudnn/cudnn-7.0-linux-x64-v4.0-prod.tgz"
You don't need to remove the url statement, just change the url. See `cuda` package.

2016-12-06 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/cudnn/package.py
> +        includedir=os.getcwd()+'/include'
What about this comment?

2016-12-06 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    Quantum-ESPRESSO is an integrated suite of Open-Source computer codes for
@nvarini QE was not removed from the changes

2016-12-06 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pytest/package.py
> +# This is a template package file for Spack.  We've put "FIXME"
FIXME is still there

2016-12-06 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pytest/package.py
> +    # FIXME: Add dependencies if this package requires them.
Also here

2016-12-06 09:29 UTC, alalazo commented on var/spack/repos/builtin/packages/py-pytest/package.py
> +    # depends_on("foo")
Also here

2016-12-06 16:29 UTC, alalazo commented
Intel still not working, but merging anyhow

2016-12-06 16:29 UTC, merged