Quantum-Espresso/6.0
epfl-scitas/spack pull request #60
Opened 2017-02-17 09:53 UTC by nvarini

2017-02-22 14:09 UTC, alalazo requested changes
Imho `intel-mkl` and `intelmpi` shouldn't be part of this PR. 

If we want to include them we should conform to what is done for other `intel` packages. This means e.g. writing a package along the line of `intel-parallel-studio` for `intel-mpi` that provides only `mpi`.

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/elpa/package.py
> +        shutil.copytree('private_modules', join_path(prefix.include,'private_modules'))
use `llnl.util.filesystem.install_tree` instead of `shutil.copytree` as it also sets the correct permissions.

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/elpa/package.py
> +        shutil.copytree('modules', join_path(prefix.include,'modules'))
Are these two lines needed for the new version? I mean: are the developers still providing a tarball that is not fixed?

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/elpa/package.py
> +    version('2016.05.004', 'c0dd3a53055536fc3a2a221e78d8b376', url='https://elpa.mpcdf.mpg.de/html/Releases/2016.05.004/elpa-2016.05.004.tar.gz')
I think it's better to implement an `url_for_version` method, rather than specifying the `url` at every new version added.

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    Quantum-ESPRESSO is an integrated suite of Open-Source computer codes for
All the other packages start docs immediately after the quotes, please revert this change.

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +        '5.4.0','8bb78181b39bd084ae5cb7a512c1cfe7',url='http://www.qe-forge.org/gf/download/frsrelease/211/968/espresso-5.4.0.tar.gz'
Same as `elpa`: I think `url_for_version` needs to be coded here.

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    variant('elpa', default=False, description='Uses elpa as an eigenvalue solver')
Why did you change the default?

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    depends_on('fftw+mpi', when='+mpi')#same as above
Maybe we should modify `mkl` to provide `fftw`?

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +            options.append('--with-elpa-lib=%s'% spec['elpa'].prefix.lib+'/libelpa_openmp.a')
Construct paths using `join_path` and avoid explicit `/` in the path.

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +          options.append('MPIF90=mpiifort')
Indent four spaces. This seems two spaces on github review.

2017-02-22 14:09 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +        #                        dependency_spec.prefix.lib64])
Remove commented code. I think it will only confuse people. In case it's needed write a comment explaining why you do something.

2017-02-22 15:28 UTC, nvarini commented on var/spack/repos/builtin/packages/elpa/package.py
> +        shutil.copytree('modules', join_path(prefix.include,'modules'))
There are still files needed from the private_modules. In general elpa install things in weird way: the include directory has the shape include/elpa-version-variant/modules.
IMHO it would be ok to copy modules and private_modules under the include directory since we don't install 2 versions in the same include directory. What do you thing?

2017-02-23 07:00 UTC, alalazo commented
@nvarini The fact that you **delete** intel-mkl makes it part of this PR too 😄

2017-02-23 07:05 UTC, alalazo commented on var/spack/repos/builtin/packages/elpa/package.py
> +        shutil.copytree('modules', join_path(prefix.include,'modules'))
If elpa want to install things that way (and I agree it's weird), I think it's responsibility of the packages using elpa to include the right folders. Do we have a finer control on where we install things with elpa? If elpa uses configure from autotools we may try that...

2017-02-23 08:22 UTC, nvarini commented on var/spack/repos/builtin/packages/espresso/package.py
> +    depends_on('fftw+mpi', when='+mpi')#same as above
No, mkl provides DFTI which is the intel FFT interface. We are not using FFTW in mkl library.

2017-02-24 10:32 UTC, alalazo requested changes
`elpa` doesn't fetch, so `espresso`. In one case it seems there are wrong urls, in the other wrong checksums. Did you try them?

For cornalin I enabled the same checks that we use in LLNL/develop. There are style checks that doesn't pass: can you please fix them? You can go to the log clicking on travis below in the page and then browsing the details of the CI.

2017-02-24 10:32 UTC, alalazo commented on var/spack/repos/builtin/packages/elpa/package.py
> +        return '%s/elpa-%s.tar.gz' % \
The `url` is wrong (`elpa` doesn't fetch)

2017-02-24 10:32 UTC, alalazo commented on var/spack/repos/builtin/packages/elpa/package.py
> +import shutil
`shutil` is imported and never used?

2017-02-24 10:32 UTC, alalazo commented on var/spack/repos/builtin/packages/elpa/package.py
> +    base_url = 'http://elpa.mpcdf.mpg.de/html/Releases'
`url` is needed here. Please don't rename it. You may have a look at `boost` as an example of a package using `url_for_version`.

2017-02-24 10:32 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    base_url = 'http://qe-forge.org/gf/download/frsrelease'
See above.

2017-02-24 10:32 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +            (Espresso.base_url,versions[str(version)], version)
`espresso` doesn't fetch:
```
Error while fetching espresso@6.0
  md5 checksum failed for /home/culpo/github/spack-scitas/var/spack/stage/espresso-6.0-dufgyszqvpytdyhl7znz346m4i7vra6i/1044-qe-6.0.tar.gz
```

2017-02-24 10:32 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    variant('elpa', default=False, description='Uses elpa as an eigenvalue solver')
Can you please add a comment explaining why you changed the default? That would help getting the changeset accepted upstream.

2017-02-24 11:52 UTC, nvarini commented on var/spack/repos/builtin/packages/espresso/package.py
> +    variant('elpa', default=False, description='Uses elpa as an eigenvalue solver')
Well deciding if this variant has to be set as default is debatable. The default would be the most common configuration used by the user or the most optimized?

2017-02-24 11:53 UTC, nvarini commented on var/spack/repos/builtin/packages/elpa/package.py
> +import shutil
I removed it

2017-02-24 11:54 UTC, nvarini commented on var/spack/repos/builtin/packages/elpa/package.py
> +    base_url = 'http://elpa.mpcdf.mpg.de/html/Releases'
The url_for_version should not replace url?

2017-03-07 12:57 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    base_url = 'http://qe-forge.org/gf/download/frsrelease'
Can you please fix this last part and restore `url`?

2017-03-07 13:08 UTC, nvarini commented on var/spack/repos/builtin/packages/espresso/package.py
> +    base_url = 'http://qe-forge.org/gf/download/frsrelease'
Why do you want to restore the url? It should work with every combination.

2017-03-07 14:22 UTC, alalazo commented on var/spack/repos/builtin/packages/espresso/package.py
> +    base_url = 'http://qe-forge.org/gf/download/frsrelease'
Because, as we discussed already, there are commands that depend on `url` being defined. On this branch:
```console
$ spack checksum espresso
==> Error: Cannot fetch versions for package Espresso because it does not define any URLs to fetch.
```

2017-03-07 14:55 UTC, alalazo commented
@nvarini You added back `intelmpi`. Can you please remove it again?

2017-03-08 11:42 UTC, alalazo approved these changes

2017-03-08 11:50 UTC, merged