Yambo package
epfl-scitas/spack pull request #75
Opened 2017-05-19 15:08 UTC by nvarini

2017-06-06 11:28 UTC, alalazo requested changes
Can you rebase this and make it pass CI tests?

2017-06-12 14:55 UTC, alalazo requested changes
:+1: For Travis and docs. Still needs some work imo.

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +    variant('mpi', default=True, description='Builds with mpi support')
Here you introduce a variant that is never used throughout the recipe. Can you please either remove it or (preferably), modify the recipe so that it could build the serial version of the software?

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +    depends_on('mpi')
`depends_on('mpi', when='+mpi')` ? Similarly for `scalapack` and other dependencies.

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +    depends_on('hdf5')
Does this package support `hdf5+mpi`, or just serial, or both?

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +            scalapack_libs = str(spec['scalapack'].libs)
Why do you need this conditional? Wouldn't the first case cover both?

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +                "--with-netcdf-libs=-L%s -lnetcdf" %
Look at the `libs` property of specs for doing things like this. Usually it results in more readable and portable code. Feel free to ping me for an explanation of this if it is not clear.

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +                "--with-blacs-libs=%s" % scalapack_libs,
Is `intel-mkl` always using `blacs` or there are cases that this recipe doesn't cover yet?

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +            args.append("--enable-open-mp")
Is this a typo or do they really put a dash? :smile:

2017-06-12 14:55 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +        make('all', parallel=False)
Just to be sure: to install `yambo` you need to run `make all` ? According to the [docs](http://www.yambo-code.org/download/installing.php) it seems you need to copy files from the build directory to the prefix...

2017-06-13 06:43 UTC, nvarini commented on var/spack/repos/builtin/packages/yambo/package.py
> +    variant('mpi', default=True, description='Builds with mpi support')
I would vote for just remove the variant. The code is so expensive that it would be super hard to run in serial.

2017-06-13 06:44 UTC, nvarini commented on var/spack/repos/builtin/packages/yambo/package.py
> +            scalapack_libs = str(spec['scalapack'].libs)
The first one is needed for intel, for gcc the second one could do. i can try to use just the first one.

2017-06-13 06:46 UTC, nvarini commented on var/spack/repos/builtin/packages/yambo/package.py
> +            args.append("--enable-open-mp")
unfortunatel the second:)

2017-06-13 07:27 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +    variant('mpi', default=True, description='Builds with mpi support')
Fine with me.

2017-06-13 12:43 UTC, nvarini commented on var/spack/repos/builtin/packages/yambo/package.py
> +    depends_on('hdf5')
serial hdf5

2017-06-19 12:26 UTC, alalazo commented on var/spack/repos/builtin/packages/yambo/package.py
> +    depends_on('hdf5')
Then you need to say:
```python
depends_on('hdf5~mpi')
```

2017-06-19 13:04 UTC, alalazo commented
@nvarini I tried to install yambo on fidis, with the GNU stack. It's failing with the errors reported below. Can you have a look at it?

```console
spack install -v -j 4 yambo@4.1.3~openmp ^netcdf-fortran@4.4.4 ^netcdf@4.4.1.1~mpi ^hdf5@1.10.1+szip~mpi~cxx ^fftw@3.3.6-pl2+mpi~openmp ^mvapich2@2.2 fabrics=mrail process_managers=slurm ^openblas %gcc@5.4.0

# ... things not reported

==> 'make' 'all'
for target in yambo_kerr yambo_ph ypp_ph; do make $target ; done
make[1]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3'
 
>>>[Making slatec]<<<
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/slatec/.objects’ and ‘lib/slatec/.objects’ are the same file
<command-line>:0:11: warning: ISO C99 requires whitespace after the macro name
make[2]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/slatec'
cd /home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/slatec; /home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/sbin/moduledep.sh avint.o xermsg.o fdump.o j4save.o xercnt.o xerhlt.o xerprn.o xersve.o i1mach.o xgetua.o polfit.o pcoef.o pvalue.o besj0.o besj1.o besk0.o besk1.o csevl.o inits.o r1mach.o besi0.o besk0e.o besi1.o besk1e.o besi0e.o besi1e.o qage.o qag.o qk15.o qk21.o qk31.o qk41.o qk51.o qk61.o qpsrt.o qawo.o qawoe.o qc25f.o qelg.o qcheb.o qwgtf.o qk15w.o qwgtf.o sgtsl.o > /tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/slatec/make.dep
make[2]: Leaving directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/slatec'
make[2]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/slatec'
avint.f xermsg.f fdump.f j4save.f xercnt.f xerhlt.f xerprn.f xersve.f i1mach.f xgetua.f polfit.f pcoef.f pvalue.f besj0.f besj1.f besk0.f besk1.f csevl.f inits.f r1mach.f besi0.f besk0e.f besi1.f besk1e.f besi0e.f besi1e.f qage.f qag.f qk15.f qk21.f qk31.f qk41.f qk51.f qk61.f qpsrt.f qawo.f qawoe.f qc25f.f qelg.f qcheb.f qwgtf.f qk15w.f sgtsl.f ar: creating libslatec.a
make[2]: Leaving directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/slatec'
 
>>>[Making local]<<<
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/local/.objects’ and ‘lib/local/.objects’ are the same file
<command-line>:0:10: warning: ISO C99 requires whitespace after the macro name
make[2]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/local'
cd /home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/local; /home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/sbin/moduledep.sh dlaran.o cgemv_omp.o dgemv_omp.o sgemv_omp.o zgemv_omp.o cgemm_omp.o zgemm_omp.o > /tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/local/make.dep
make[2]: Leaving directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/local'
make[2]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/local'
dlaran.f cgemv_omp.f dgemv_omp.f sgemv_omp.f zgemv_omp.f cgemm_omp.f zgemm_omp.f ar: creating liblocal.a
make[2]: Leaving directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/local'
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/archive/Makefile.loc’ and ‘lib/archive/Makefile.loc’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/archive/package.list’ and ‘lib/archive/package.list’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/config/missing’ and ‘config/missing’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/install/iotk_specials.h’ and ‘lib/install/iotk_specials.h’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/install/make_iotk.inc’ and ‘lib/install/make_iotk.inc’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/install/make_iotk.inc.in’ and ‘lib/install/make_iotk.inc.in’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/iotk/Makefile.loc’ and ‘lib/iotk/Makefile.loc’ are the same file
 
>>>[Making iotk]<<<
make[2]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/iotk'
( cd ../archive ; if ! test -e iotk-y1.2.1.tar.gz ; then \
cp Makefile.loc Makefile ; make iotk-y1.2.1.tar.gz ; fi )
make[3]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/archive'
--2017-06-19 14:57:46--  https://github.com/yambo-code/yambo/files/783147/iotk-y1.2.1.tar.gziotk-y1.2.1.tar.gz
Resolving fadmin1 (fadmin1)... 10.91.10.254
Connecting to fadmin1 (fadmin1)|10.91.10.254|:80... connected.
Proxy tunneling failed: Bad RequestUnable to establish SSL connection.
make[3]: *** [iotk-y1.2.1.tar.gz] Error 4
make[3]: Leaving directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/archive'
make[2]: *** [uncompress-stamp] Error 2
make[2]: Leaving directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3/lib/iotk'
make[1]: *** [libs] Error 2
make[1]: Leaving directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3'
make[1]: Entering directory `/tmp/pytest-of-culpo/pytest-0/test_keep_exceptions0/tmp/spack-stage/spack-stage-HODyh7/yambo-4.1.3'
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/archive/iotk-y1.2.1.tar.gz’ and ‘lib/archive/iotk-y1.2.1.tar.gz’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/archive/Makefile’ and ‘lib/archive/Makefile’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/archive/Makefile.loc’ and ‘lib/archive/Makefile.loc’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/archive/package.list’ and ‘lib/archive/package.list’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/config/missing’ and ‘config/missing’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjeen5latr7lmxv4ep/yambo-4.1.3/lib/install/iotk_specials.h’ and ‘lib/install/iotk_specials.h’ are the same file
cp: ‘/home/culpo/installation-tests/cornalin/spack/var/spack/stage/yambo-4.1.3-kq5yebuidubcssdjee [...]

2017-06-19 13:07 UTC, nvarini commented
Yes that was the error I was mentioned by voice.
On deneb it does not get stuck with this error.
Basically the file ../archive/iotk-y1.2.1.tar.gz is empty, it seems that for some reason it fails to download.
Any idea why?

2017-07-05 11:31 UTC, alalazo approved these changes

2017-07-05 12:16 UTC, merged